import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={"max-w-[1000px] mx-auto"}>

      <body className={inter.className + "w-full flex flex-col justify-start"}>
      <h1 className={"text-black w-fit flex flex-col items-start"}>Nav</h1>
      {children}</body>
    </html>
  );
}
